<a href="https://colab.research.google.com/github/Tobaho/Tobaho.github.io/blob/main/Integers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Integers and Float

I will start by importing my data sets

In [2]:
import pandas as pa
import statistics as stat
df = pa.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df.head().T

                       0            1            2            3            4
SepalLength          5.1          4.9          4.7          4.6          5.0
SepalWidth           3.5          3.0          3.2          3.1          3.6
PedalLength          1.4          1.4          1.3          1.5          1.4
PedalWidth           0.2          0.2          0.2          0.2          0.2
Class        Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

* Does converting SepalLength to integer increase or decrease the mean

In [8]:
df.SepalLength.agg(['mean'])

mean    5.843333
Name: SepalLength, dtype: float64

In [10]:

print("as int: ", stat.mean(df.SepalLength.astype('int')))

as int:  5.386666666666667

After converting, it decreases the mean.

* Does the direction of the shift remain the same if you groupby Class?

In [17]:
df.SepalLength = df.SepalLength.astype('int')
df.groupby('Class').SepalLength.agg(['mean'])

                 mean
Class
Iris-setosa      4.60
Iris-versicolor  5.48
Iris-virginica   6.08

From the above, I think the direction of shift remails the same

* Gather the mean, median, count and standard deviation of all columns when grouped by Class.

In [18]:
df.groupby('Class').agg(['mean','median','count', 'std'])

                SepalLength               ... PedalWidth
                       mean median count  ...     median count       std
Class                                     ...
Iris-setosa            4.60    5.0    50  ...        0.2    50  0.107210
Iris-versicolor        5.48    5.0    50  ...        1.3    50  0.197753
Iris-virginica         6.08    6.0    50  ...        2.0    50  0.274650

[3 rows x 16 columns]